pipeline {
    agent any
    triggers {
        pollSCM('H/2 * * * *' )
    }
    tools{
        maven 'Maven 3.6.1'
    }

    stages {  
        stage('Build'){
            steps { 
                echo 'Building..'
                sh 'mvn -f worker/pom.xml compile'
            }
        }
    }
    stage('Test'){
         steps {
                echo 'Packaging..'
                sh 'mvn -f worker/pom.xml test'
            }
    }
    stage('Package'){
         steps {
                echo 'Testing..'
                sh 'mvn -f worker/pom.xml package -DiskipTests'
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
    }
    posts{
        always{
            echo 'Buliding multibranch and pipeline for users is complated'
        }
    }
}

 