pipeline{
      agent{
         docker{
           image 'maven:3.6.1-jdk-8-slim'
           args '-v $HOME/.m2:/root/.m2'
         }
}
      stages{
          stage('build'){
              steps{
                  echo 'building users app'
                  dir('java/cmad-ms-users'){
                    sh 'mvn compile'
                  }
} }
stage('test'){

  steps{
                  echo 'running unit tests on users app'
                  dir('java/cmad-ms-users'){
                    sh 'mvn clean test'
                  }
} }
          stage('package'){
              steps{
                  echo 'packaging users app into a jarfile'
                  dir('java/cmad-ms-users'){
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: 'java/cmad-ms-users/target/
  *.jar', fingerprint: true
} }
} }
      post{
          always{
              echo 'the job is complete'
          }
} }